version: 1.0.{build}
skip_non_tags: false
image: Visual Studio 2017
configuration: Release
init:
- ps: "function gitVersion() {\n  write-host \"Setting version according to the git release tag.\"\n\n  $branch=$env:APPVEYOR_REPO_TAG_NAME\n    \n  $posAfterVchar = $branch.LastIndexOf(\"v\") + 1\n  $versionLength = $branch.Length - $posAfterVchar\n      \n  $gitVersion=$branch.substring($posAfterVchar, $versionLength)\n      \n  $newVersion=\"$gitVersion\"\n     \n  write-host \"Update appveyor build version to:$newVersion\"\n  $env:appveyor_build_version=\"$newVersion\"\n  appveyor UpdateBuild -Version \"$newVersion\"\n}\nif ($env:APPVEYOR_REPO_TAG -eq $true)\n{\n  gitVersion\n}"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore

    nuget restore
build:
  verbosity: minimal
test: off
artifacts:
- path: UDProtean\**\.nupkg
  name: NuGet
deploy:
- provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: U909gTvHqZ0NpnlX9zlt7uIjpgecLfDAixvOtApwnfVYseBihEUBnR3mSqV9ASzY
